// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc1939.AerialAssist2014.subsystems;
import org.usfirst.frc1939.AerialAssist2014.RobotMap;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
/**
 *
 */
public class Catapult extends Subsystem {
    
    public boolean magnet_on = false;
    
    public final double pressurizeDelay = 0.3;
    public final double depressurizeDelay = 0.2;
    
    public final double catapultKickSpeed = 1.0;
    public final double limitSwitchDelay = 0.3;
    
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    DoubleSolenoid rightSolenoid = RobotMap.catapultRightSolenoid;
    DoubleSolenoid leftSolenoid = RobotMap.catapultLeftSolenoid;
    SpeedController magnet = RobotMap.catapultMagnet;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    public void pressurize(){
        rightSolenoid.set(DoubleSolenoid.Value.kForward);
        leftSolenoid.set(DoubleSolenoid.Value.kForward);
    }
    
    public void depressurize(){
        rightSolenoid.set(DoubleSolenoid.Value.kReverse);
        leftSolenoid.set(DoubleSolenoid.Value.kReverse);
    }
}
