// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc1939.AerialAssist2014.subsystems;
import org.usfirst.frc1939.AerialAssist2014.RobotMap;
import org.usfirst.frc1939.AerialAssist2014.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
/**
 *
 */
public class Lights extends Subsystem {
    
    public final int OFF = 0;
    public final int GREEN = 1;
    public final int RED = 2;
    public final int PURPLE = 3;
    
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    Relay spikeOne = RobotMap.lightsSpikeOne;
    Relay spikeTwo = RobotMap.lightsSpikeTwo;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    
    //Relay 2 is green
    //Relay 3 is red
    public void setColor(int color){
        if(color == 0){
            spikeOne.set(Relay.Value.kOff);
            spikeTwo.set(Relay.Value.kOff);
        }else if(color == 1){
            spikeOne.set(Relay.Value.kOn);
            spikeTwo.set(Relay.Value.kOff);
        }else if (color == 2){
            spikeOne.set(Relay.Value.kOff);
            spikeTwo.set(Relay.Value.kOn);
        }else if(color == 3){
            spikeOne.set(Relay.Value.kOn);
            spikeTwo.set(Relay.Value.kOn);
        }
    }
    
    public void setGreen(){
        setColor(GREEN);
    }
    
    public void setRed(){
        setColor(RED);
    }
    
    public void setPurple(){
        setColor(PURPLE);
    }
    
    public void setOff(){
        setColor(OFF);
    }
}
