// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc1939.AerialAssist2014.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc1939.AerialAssist2014.Robot;
import org.usfirst.frc1939.AerialAssist2014.RobotMap;
/**
 *
 */
public class  DriveByInches extends Command {
    private final double inches;
    private final int angle;
    
    public DriveByInches(int angle, double inches) {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
	
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.drivetrain);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        this.inches = inches;
        this.angle = angle;
        
    }
    // Called just before this Command runs the first time
    protected void initialize() {
        Robot.drivetrain.zeroEncoders();
    }
    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        // Drive Speed - Degree - Turn Speed
        RobotMap.drivetrainRobotDrive.mecanumDrive_Polar(Robot.drivetrain.autonomousDriveSpeed, angle, 0.0);
    }
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        System.out.println("Inches: " + Robot.drivetrain.getDistance());
        System.out.println("Encoder: " + RobotMap.drivetrainLeftBackEncoder.get());
        System.out.println("Distance from Encoder: " + RobotMap.drivetrainLeftBackEncoder.getDistance());
        return Robot.drivetrain.getDistance()>= inches;
    }
    // Called once after isFinished returns true
    protected void end() {
        RobotMap.drivetrainRobotDrive.mecanumDrive_Cartesian(0, 0, 0, 0);
    }
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
